# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'BSH' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



  # Pods for BSH

pod 'Prototyper'
pod 'CUU'
pod 'SwaggerClient', :path => './SwaggerClient'
pod "TouchVisualizer"
pod 'Firebase/Core'


end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.new_shell_script_build_phase.shell_script = "mkdir -p $PODS_CONFIGURATION_BUILD_DIR/#{target.name}"
        target.build_configurations.each do |config|
            config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
        end
    end
end
