//
// Annotation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Annotation: Codable {

    public var _id: String
    public var points: [Point]
    public var type: String
    public var label: String
    public var userId: String
    public var campaignId: String
    public var imageId: String
    public var timestamp: String?

    public init(_id: String, points: [Point], type: String, label: String, userId: String, campaignId: String, imageId: String, timestamp: String?) {
        self._id = _id
        self.points = points
        self.type = type
        self.label = label
        self.userId = userId
        self.campaignId = campaignId
        self.imageId = imageId
        self.timestamp = timestamp
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case points
        case type
        case label
        case userId
        case campaignId
        case imageId
        case timestamp
    }


}

