//
// AnnotationCreationRequestItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AnnotationCreationRequestItem: Codable {

    public var points: [Point]
    public var type: String
    public var label: String

    public init(points: [Point], type: String, label: String) {
        self.points = points
        self.type = type
        self.label = label
    }


}

