//
// CampaignUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignUpdateRequest: Codable {

    public var userToken: String
    public var campaign: Campaign

    public init(userToken: String, campaign: Campaign) {
        self.userToken = userToken
        self.campaign = campaign
    }


}

