//
// CampaignCreationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CampaignCreationRequest: Codable {

    public var userToken: String
    public var type: CampaignType
    public var name: String
    public var urlName: String?
    public var _description: String
    public var taxonomy: [String]
    public var image: String
    public var ownerId: String?

    public init(userToken: String, type: CampaignType, name: String, urlName: String?, _description: String, taxonomy: [String], image: String, ownerId: String?) {
        self.userToken = userToken
        self.type = type
        self.name = name
        self.urlName = urlName
        self._description = _description
        self.taxonomy = taxonomy
        self.image = image
        self.ownerId = ownerId
    }

    public enum CodingKeys: String, CodingKey { 
        case userToken
        case type
        case name
        case urlName
        case _description = "description"
        case taxonomy
        case image
        case ownerId
    }


}

