//
// Campaign.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Campaign: Codable {

    public var _id: Int
    public var ownerId: Int
    public var type: CampaignType
    public var name: String
    public var _description: String
    public var vocabulary: [String]
    public var userIds: [Double]

    public init(_id: Int, ownerId: Int, type: CampaignType, name: String, _description: String, vocabulary: [String], userIds: [Double]) {
        self._id = _id
        self.ownerId = ownerId
        self.type = type
        self.name = name
        self._description = _description
        self.vocabulary = vocabulary
        self.userIds = userIds
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case ownerId
        case type
        case name
        case _description = "description"
        case vocabulary
        case userIds
    }


}

