//
// ImageData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImageData: Codable {

    public var _id: String
    public var campaignId: String
    public var userId: String
    public var annotations: [Annotation]
    public var timestamp: String
    public var url: String

    public init(_id: String, campaignId: String, userId: String, annotations: [Annotation], timestamp: String, url: String) {
        self._id = _id
        self.campaignId = campaignId
        self.userId = userId
        self.annotations = annotations
        self.timestamp = timestamp
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case campaignId
        case userId
        case annotations
        case timestamp
        case url
    }


}

