//
// ImageData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImageData: Codable {

    public var _id: Double
    public var campaignId: Double
    public var userId: Double
    public var annotations: [Annotation]

    public init(_id: Double, campaignId: Double, userId: Double, annotations: [Annotation]) {
        self._id = _id
        self.campaignId = campaignId
        self.userId = userId
        self.annotations = annotations
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case campaignId
        case userId
        case annotations
    }


}

