//
// Leaderboard.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Leaderboard: Codable {

    public var _id: String
    public var campaignId: String
    public var scores: [LeaderboardScore]

    public init(_id: String, campaignId: String, scores: [LeaderboardScore]) {
        self._id = _id
        self.campaignId = campaignId
        self.scores = scores
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case campaignId
        case scores
    }


}

