//
// LeaderboardCreationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LeaderboardCreationRequest: Codable {

    public var campaignId: String
    public var userToken: String
    public var scores: [LeaderboardScore]

    public init(campaignId: String, userToken: String, scores: [LeaderboardScore]) {
        self.campaignId = campaignId
        self.userToken = userToken
        self.scores = scores
    }


}

