//
// LeaderboardUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LeaderboardUpdateRequest: Codable {

    public var userToken: String
    public var leaderboard: Leaderboard

    public init(userToken: String, leaderboard: Leaderboard) {
        self.userToken = userToken
        self.leaderboard = leaderboard
    }


}

