//
// LeaderboardScore.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LeaderboardScore: Codable {

    public var userId: String
    public var score: Double

    public init(userId: String, score: Double) {
        self.userId = userId
        self.score = score
    }


}

