//
// PredictionResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PredictionResult: Codable {

    public var predictionURL: String

    public init(predictionURL: String) {
        self.predictionURL = predictionURL
    }


}

