//
// TrainingCreationRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TrainingCreationRequest: Codable {

    public var userToken: String
    public var training: Training

    public init(userToken: String, training: Training) {
        self.userToken = userToken
        self.training = training
    }


}

