//
// Training.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Training: Codable {

    public var _id: String
    public var campaignId: String
    public var timeStart: String
    public var currentEpoch: Double
    public var epochs: Double
    public var currentStep: Double
    public var steps: Double
    public var metrics: [String]
    public var finished: Bool

    public init(_id: String, campaignId: String, timeStart: String, currentEpoch: Double, epochs: Double, currentStep: Double, steps: Double, metrics: [String], finished: Bool) {
        self._id = _id
        self.campaignId = campaignId
        self.timeStart = timeStart
        self.currentEpoch = currentEpoch
        self.epochs = epochs
        self.currentStep = currentStep
        self.steps = steps
        self.metrics = metrics
        self.finished = finished
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case campaignId
        case timeStart
        case currentEpoch
        case epochs
        case currentStep
        case steps
        case metrics
        case finished
    }


}

