//
// TrainingUpdateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TrainingUpdateRequest: Codable {

    public var currentEpoch: Double
    public var currentStep: Double
    public var finished: Bool
    public var metric: String

    public init(currentEpoch: Double, currentStep: Double, finished: Bool, metric: String) {
        self.currentEpoch = currentEpoch
        self.currentStep = currentStep
        self.finished = finished
        self.metric = metric
    }


}

