//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: String
    public var email: String

    public init(_id: String, email: String) {
        self._id = _id
        self.email = email
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case email
    }


}

